name: jmap_dart_client
description: A JMAP client library to make JMAP method calls and process the responses.
version: 0.4.0
homepage: https://github.com/leithmail/jmap-dart-client.git

environment:
  sdk: ^3.8.0

dependencies:
  built_collection: ^5.1.1
  equatable: ^2.0.5
  http: ^1.6.0
  http_parser: ^4.1.0
  json_annotation: ^4.11.0
  quiver: ^3.2.1

dev_dependencies:
  build_runner: ^2.13.1
  collection: ^1.18.0
  coverage: ^1.15.0
  httptest: ^0.13.30
  json_serializable: 6.13.1
  test: ^1.31.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
